#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_sourcepp = env_modules.Clone()

if env.msvc:
	env_sourcepp.AppendUnique(CXXFLAGS=["/std:c++20"])
else:
	env_sourcepp.AppendUnique(CXXFLAGS=["-std=c++20"])

thirdparty_obj = []

thirdparty_dir = "#thirdparty/sourcepp/"
xz_dir = "#thirdparty/xz/"
thirdparty_sources = [
	thirdparty_dir + "src/sourcepp/FS.cpp",
	thirdparty_dir + "src/sourcepp/String.cpp",
	thirdparty_dir + "src/sourcepp/compression/LZMA.cpp",
	thirdparty_dir + "src/sourcepp/parser/Binary.cpp",
	thirdparty_dir + "src/sourcepp/parser/Text.cpp",
	thirdparty_dir + "src/sourcepp/crypto/AES.cpp",
	thirdparty_dir + "src/sourcepp/crypto/Adler32.cpp",
	thirdparty_dir + "src/sourcepp/crypto/CRC32.cpp",
	thirdparty_dir + "src/sourcepp/crypto/MD5.cpp",
	thirdparty_dir + "src/sourcepp/crypto/RSA.cpp",
	thirdparty_dir + "src/sourcepp/crypto/SHA1.cpp",
	thirdparty_dir + "src/sourcepp/crypto/SHA256.cpp",
	thirdparty_dir + "src/kvpp/KV1Binary.cpp",
	thirdparty_dir + "src/bsppp/BSP.cpp",
	thirdparty_dir + "src/bsppp/EntityLump.cpp",
	thirdparty_dir + "src/mdlpp/mdlpp.cpp",
	thirdparty_dir + "src/mdlpp/structs/MDL.cpp",
	thirdparty_dir + "src/mdlpp/structs/VTX.cpp",
	thirdparty_dir + "src/mdlpp/structs/VVD.cpp",
	thirdparty_dir + "src/steampp/steampp.cpp",
	thirdparty_dir + "src/fspp/fspp.cpp",
	thirdparty_dir + "src/vpkpp/PackFile.cpp",
	thirdparty_dir + "src/vpkpp/format/VPK.cpp",
	thirdparty_dir + "src/vtfpp/HOT.cpp",
	thirdparty_dir + "src/vtfpp/ImageConversion.cpp",
	thirdparty_dir + "src/vtfpp/ImageQuantize.cpp",
	thirdparty_dir + "src/vtfpp/SHT.cpp",
	thirdparty_dir + "src/vtfpp/VTF.cpp",
	xz_dir + "src/tuklib_physmem.c",
	xz_dir + "src/liblzma/check/check.c",
	xz_dir + "src/liblzma/check/crc32_fast.c",
	xz_dir + "src/liblzma/common/common.c",
	xz_dir + "src/liblzma/common/block_util.c",
	xz_dir + "src/liblzma/common/easy_preset.c",
	xz_dir + "src/liblzma/common/filter_common.c",
	xz_dir + "src/liblzma/common/hardware_physmem.c",
	xz_dir + "src/liblzma/common/index.c",
	xz_dir + "src/liblzma/common/stream_flags_common.c",
	xz_dir + "src/liblzma/common/string_conversion.c",
	xz_dir + "src/liblzma/common/vli_size.c",
	xz_dir + "src/liblzma/common/alone_encoder.c",
	xz_dir + "src/liblzma/common/block_buffer_encoder.c",
	xz_dir + "src/liblzma/common/block_encoder.c",
	xz_dir + "src/liblzma/common/block_header_encoder.c",
	xz_dir + "src/liblzma/common/easy_buffer_encoder.c",
	xz_dir + "src/liblzma/common/easy_encoder.c",
	xz_dir + "src/liblzma/common/easy_encoder_memusage.c",
	xz_dir + "src/liblzma/common/filter_buffer_encoder.c",
	xz_dir + "src/liblzma/common/filter_encoder.c",
	xz_dir + "src/liblzma/common/filter_flags_encoder.c",
	xz_dir + "src/liblzma/common/index_encoder.c",
	xz_dir + "src/liblzma/common/stream_buffer_encoder.c",
	xz_dir + "src/liblzma/common/stream_encoder.c",
	xz_dir + "src/liblzma/common/stream_flags_encoder.c",
	xz_dir + "src/liblzma/common/vli_encoder.c",
	xz_dir + "src/liblzma/common/alone_decoder.c",
	xz_dir + "src/liblzma/common/auto_decoder.c",
	xz_dir + "src/liblzma/common/block_buffer_decoder.c",
	xz_dir + "src/liblzma/common/block_decoder.c",
	xz_dir + "src/liblzma/common/block_header_decoder.c",
	xz_dir + "src/liblzma/common/easy_decoder_memusage.c",
	xz_dir + "src/liblzma/common/file_info.c",
	xz_dir + "src/liblzma/common/filter_buffer_decoder.c",
	xz_dir + "src/liblzma/common/filter_decoder.c",
	xz_dir + "src/liblzma/common/filter_flags_decoder.c",
	xz_dir + "src/liblzma/common/index_decoder.c",
	xz_dir + "src/liblzma/common/index_hash.c",
	xz_dir + "src/liblzma/common/stream_buffer_decoder.c",
	xz_dir + "src/liblzma/common/stream_decoder.c",
	xz_dir + "src/liblzma/common/stream_flags_decoder.c",
	xz_dir + "src/liblzma/common/vli_decoder.c",
	xz_dir + "src/liblzma/lz/lz_encoder.c",
	xz_dir + "src/liblzma/lz/lz_encoder_mf.c",
	xz_dir + "src/liblzma/lz/lz_decoder.c",
	xz_dir + "src/liblzma/lzma/lzma_encoder_presets.c",
	xz_dir + "src/liblzma/lzma/lzma_encoder.c",
	xz_dir + "src/liblzma/lzma/lzma_encoder_optimum_fast.c",
	xz_dir + "src/liblzma/lzma/lzma_encoder_optimum_normal.c",
	xz_dir + "src/liblzma/lzma/fastpos_table.c",
	xz_dir + "src/liblzma/lzma/lzma_decoder.c",
	xz_dir + "src/liblzma/rangecoder/price_table.c",
]

env_sourcepp.Prepend(CPPPATH=[
	"#thirdparty/bufferstream/include",
	"#thirdparty/mbedtls/include",
	"#thirdparty/misc",
	"#thirdparty/zstd",
	thirdparty_dir + "include",
	thirdparty_dir + "ext/half/include",
	thirdparty_dir + "ext/stb/include",
	xz_dir,
	xz_dir + "src",
	xz_dir + "src/liblzma/api",
	xz_dir + "src/liblzma/common",
	xz_dir + "src/liblzma/check",
	xz_dir + "src/liblzma/lz",
	xz_dir + "src/liblzma/lzma",
	xz_dir + "src/liblzma/delta",
	xz_dir + "src/liblzma/rangecoder",
	xz_dir + "src/liblzma/simple",
])

env_thirdparty = env_sourcepp.Clone()
env_thirdparty.AppendUnique(CPPDEFINES=[
	"HAVE_CONFIG_H",
	"LZMA_API_STATIC",
	"TUKLIB_SYMBOL_PREFIX=lzma_",
])
env_thirdparty.disable_warnings()
env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)
env.modules_sources += thirdparty_obj

module_obj = []
env_sourcepp.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

env.Depends(module_obj, thirdparty_obj)